services:
  harvest_process:
    build:
      context: .
      dockerfile: ./Dockerfiles/dev/Dockerfile
    ports:
      - ${HARVEST_PROCESS_PORT}:5000
    volumes:
      - ./:/src
      - /src/dcdump
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DB_MONGO_HOST=${DB_MONGO_HOST}
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - DB_MONGO_USER=${DB_MONGO_USER}
      - DB_MONGO_PASSWORD=${DB_MONGO_PASSWORD}
      - DB_MONGO_NAME=${DB_MONGO_NAME}
    command: bash -c "sleep 10 && python3 manage.py run -h 0.0.0.0"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.9
    ports:
      - ${DB_MONGO_PORT}:${DB_MONGO_PORT}
    volumes:
            #- ./:/data/db
            - ./mongod.conf:/etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_PASSWORD}
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - MONGO_INITDB_DATABASE:${DB_MONGO_NAME}
