services:
  harvest_process:
    build:
      context: .
      dockerfile: ./Dockerfiles/dev/Dockerfile
    ports:
      - ${HARVEST_PROCESS_PORT}:5000
    volumes:
      - ./:/src
      - /src/dcdump
    environment:
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - DB_MONGO_AUTH_MECH=${DB_MONGO_AUTH_MECH}
      - DB_MONGO_HOST=${DB_MONGO_HOST}
      - DB_MONGO_NAME=${DB_MONGO_NAME}
      - DB_MONGO_PASSWORD=${DB_MONGO_PASSWORD}
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - DB_MONGO_USER=${DB_MONGO_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - FLASK_ENV=${FLASK_ENV}
    command: bash -c "sleep 10 && python3 manage.py run -h 0.0.0.0"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.9
    ports:
      - ${DB_MONGO_PORT}:${DB_MONGO_PORT}
    volumes:
            #- ./:/data/db
            - ./mongod.conf:/etc/mongod.conf
    environment:
      - DB_MONGO_AUTH_MECH=${DB_MONGO_AUTH_MECH}
      - DB_MONGO_HOST=${DB_MONGO_HOST}
      - DB_MONGO_NAME=${DB_MONGO_NAME}
      - DB_MONGO_PASSWORD=${DB_MONGO_PASSWORD}
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - DB_MONGO_USER=${DB_MONGO_USER}
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}