# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests and linter for BSO3

on: [ push, pull_request ]

jobs:
  quality-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick
          python -m pip install --upgrade pip
          make install

      - name: Check Python syntax errors
        run: |
          # stop the build if there are Python syntax errors or undefined names
          make lint-syntax

      - name: Check style conventions
        continue-on-error: true
        run: |
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          make lint-style

      - name: Unit-Tests with pytest
        run: |
          make unit-tests
      - name: Integration-Tests with pytest
        env:
          - DB_MONGO_AUTH_MECH: ${{ secrets.DB_MONGO_AUTH_MECH }}
          - DB_MONGO_HOST: ${{ secrets.DB_MONGO_HOST }}
          - DB_MONGO_NAME: ${{ secrets.DB_MONGO_NAME }}
          - DB_MONGO_PASSWORD: ${{ secrets.DB_MONGO_PASSWORD }}
          - DB_MONGO_PORT: ${{ secrets.DB_MONGO_PORT }}
          - DB_MONGO_USER: ${{ secrets.DB_MONGO_USER }}
          - FLASK_ENV: ${{ secrets.FLASK_ENV }}
        run: |
          make docker-compose-up
          make integration-tests
          make docker-compose-down